# Configuração básica do Dovecot
protocols = imap pop3 lmtp
listen = *

# Autenticação
auth_mechanisms = plain login
auth_verbose = yes

# Maildir
mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir

# Autenticação LDAP
passdb {
  driver = ldap
  args = /etc/dovecot/dovecot-ldap.conf.ext
}

userdb {
  driver = ldap
  args = /etc/dovecot/dovecot-ldap.conf.ext
}

# Quotas
quota_rule = *:storage=100M
quota_rule2 = Trash:storage=+10%%
quota_warning = storage=95%% quota-warning 95 %u
quota_warning2 = storage=80%% quota-warning 80 %u

# Logs
log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot-info.log

# SSL/TLS
ssl = required
ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key

# Permissões
mail_uid = postfix
mail_gid = postfix
first_valid_uid = 5000
last_valid_uid = 5000
